/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/yb-theme.ts
 * Command: astryx theme build src/theme/yb-theme.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/**
 * yb theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { ybTheme } from './yb';
 *   import './yb.css';
 */
export const ybTheme = {
  name: 'yb',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#5B3FE0, #9B7BFF)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #0B0F1C)",
    "--color-neutral": "light-dark(#1B1F3B0F, #A5B4FC1A)",
    "--color-background-surface": "light-dark(#FFFFFF, #0F1528)",
    "--color-background-body": "light-dark(#F6F7FB, #0A0E1A)",
    "--color-overlay": "light-dark(#0A0E1A66, #05070D99)",
    "--color-overlay-hover": "light-dark(#1B1F3B0D, #FFFFFF12)",
    "--color-overlay-pressed": "light-dark(#1B1F3B1A, #FFFFFF1F)",
    "--color-background-muted": "light-dark(#EEF0F7, #131A30)",
    "--color-text-primary": "light-dark(#141826, #E6E8F2)",
    "--color-text-secondary": "light-dark(#525868, #A3ABC0)",
    "--color-text-disabled": "light-dark(#9AA0B2, #5D6580)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#141826, #E6E8F2)",
    "--color-icon-secondary": "light-dark(#525868, #A3ABC0)",
    "--color-icon-disabled": "light-dark(#9AA0B2, #5D6580)",
    "--color-background-card": "light-dark(#FFFFFF, #18203A)",
    "--color-background-popover": "light-dark(#FFFFFF, #1E2744)",
    "--color-background-inverted": "light-dark(#141826, #F6F7FB)",
    "--color-border": "light-dark(#1B1F3B1A, #A5B4FC24)",
    "--color-border-emphasized": "light-dark(#858CA1, #626C8D)",
    "--color-skeleton": "light-dark(#D5D9E5, #2A3350)",
    "--color-track": "light-dark(#D5D9E5, #2A3350)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.3125rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.25rem",
    "--font-size-xl": "1.5625rem",
    "--font-size-2xl": "1.9375rem",
    "--font-size-3xl": "2.4375rem",
    "--font-size-4xl": "3.0625rem",
    "--font-size-5xl": "3.8125rem",
    "--text-heading-1-size": "clamp(var(--font-size-2xl), 1.625rem + 1vw, var(--font-size-3xl))",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.15",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.28",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-normal)",
    "--text-large-leading": "1.5",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "clamp(var(--font-size-3xl), 1.9rem + 2.4vw, var(--font-size-5xl))",
    "--text-display-1-weight": "var(--font-weight-semibold)",
    "--text-display-1-leading": "1.05",
    "--text-display-2-size": "clamp(var(--font-size-2xl), 1.6rem + 1.75vw, var(--font-size-4xl))",
    "--text-display-2-weight": "var(--font-weight-semibold)",
    "--text-display-2-leading": "1.08",
    "--text-display-3-size": "clamp(var(--font-size-2xl), 1.4rem + 1.4vw, var(--font-size-3xl))",
    "--text-display-3-weight": "var(--font-weight-semibold)",
    "--text-display-3-leading": "1.12",
    "--duration-fast-min": "115ms",
    "--duration-fast": "150ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "265ms",
    "--duration-medium": "350ms",
    "--duration-medium-max": "465ms",
    "--duration-slow-min": "600ms",
    "--duration-slow": "800ms",
    "--duration-slow-max": "1065ms",
    "--font-family-body": "var(--font-fustat), -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "var(--font-fustat), -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "var(--font-jetbrains-mono), ui-monospace, \"SF Mono\", Menlo, Consolas, monospace",
    "--color-syntax-keyword": "#B49CFF",
    "--color-syntax-string": "#B7C0D8",
    "--color-syntax-comment": "#8590AD",
    "--color-syntax-number": "#C9B8FF",
    "--color-syntax-function": "#D9CCFF",
    "--color-syntax-type": "#C3CCE6",
    "--color-syntax-variable": "#E6E8F2",
    "--color-syntax-operator": "#A3ABC0",
    "--color-syntax-constant": "#C9B8FF",
    "--color-syntax-tag": "#B49CFF",
    "--color-syntax-attribute": "#D9CCFF",
    "--color-syntax-property": "#C3CCE6",
    "--color-syntax-punctuation": "#A3ABC0",
    "--color-syntax-background": "#0B1020",
    "--focus-outline-color": "var(--color-accent)",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px color-mix(in srgb, var(--color-accent) 55%, transparent)",
    "--size-element-sm": "30px",
    "--size-element-md": "36px",
    "--size-element-lg": "44px"
  },
  localTokens: {
    "--yb-motion-micro": "var(--duration-fast)",
    "--yb-motion-exit": "var(--duration-fast-min)",
    "--yb-motion-enter": "var(--duration-medium-min)",
    "--yb-motion-emphasis": "var(--duration-medium-max)",
    "--yb-motion-stagger": "calc(var(--duration-fast) * 0.2667)",
    "--yb-motion-distance": "var(--spacing-6)",
    "--yb-ease-enter": "var(--ease-standard)",
    "--yb-ease-exit": "cubic-bezier(0.4, 0, 1, 1)",
    "--yb-ease-move": "cubic-bezier(0.65, 0, 0.35, 1)",
    "--yb-prose-size": "calc(var(--font-size-base) * 1.125)",
    "--yb-heading-tracking": "-0.011em",
    "--yb-stroke-motif": "1.5px",
    "--yb-stroke-icon": "2px",
    "--yb-control-border": "light-dark(#B9BFCF, #3D4766)",
    "--yb-terminal-background": "#0B1020",
    "--yb-terminal-bar": "#111833",
    "--yb-terminal-border": "light-dark(#1B1F3B26, #A5B4FC24)",
    "--yb-terminal-text": "#E6E8F2",
    "--yb-terminal-muted": "#A3ABC0",
    "--yb-terminal-prompt": "#9B7BFF",
    "--yb-terminal-dot": "#3D4766",
    "--yb-terminal-size": "clamp(var(--font-size-sm), 0.72rem + 0.32vw, calc(var(--font-size-base) * 0.9375))"
  },
  __localTokenOwners: {
    "--yb-motion-micro": "yb",
    "--yb-motion-exit": "yb",
    "--yb-motion-enter": "yb",
    "--yb-motion-emphasis": "yb",
    "--yb-motion-stagger": "yb",
    "--yb-motion-distance": "yb",
    "--yb-ease-enter": "yb",
    "--yb-ease-exit": "yb",
    "--yb-ease-move": "yb",
    "--yb-prose-size": "yb",
    "--yb-heading-tracking": "yb",
    "--yb-stroke-motif": "yb",
    "--yb-stroke-icon": "yb",
    "--yb-control-border": "yb",
    "--yb-terminal-background": "yb",
    "--yb-terminal-bar": "yb",
    "--yb-terminal-border": "yb",
    "--yb-terminal-text": "yb",
    "--yb-terminal-muted": "yb",
    "--yb-terminal-prompt": "yb",
    "--yb-terminal-dot": "yb",
    "--yb-terminal-size": "yb"
  },
  __localTokenLineage: ["yb"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)",
        "letterSpacing": "-0.02em"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)",
        "letterSpacing": "-0.03em"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)",
        "letterSpacing": "-0.025em"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)",
        "letterSpacing": "-0.02em"
      },
      "base": {
        "letterSpacing": "var(--yb-heading-tracking)",
        "textWrap": "balance"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)",
        "textWrap": "pretty"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-10) var(--spacing-4)"
      },
      "variant:section": {
        "backgroundColor": "transparent"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-5)"
      }
    },
    "button": {
      "base": {
        "fontWeight": "var(--font-weight-semibold)"
      },
      "variant:primary": {
        ":hover": {
          "backgroundColor": "light-dark(color-mix(in srgb, var(--color-accent) 86%, black), color-mix(in srgb, var(--color-accent) 82%, white))"
        }
      },
      "variant:secondary": {
        "backgroundColor": "light-dark(var(--color-background-card), var(--color-neutral))",
        "color": "var(--color-text-primary)",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--yb-control-border)",
        ":hover": {
          "backgroundColor": "light-dark(var(--color-background-muted), var(--color-neutral))"
        }
      }
    },
    "list-item": {
      "base": {
        ":last-child": {
          "borderBottomWidth": "0"
        }
      }
    },
    "top-nav-heading": {
      "base": {
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "-0.01em"
      }
    },
    "banner": {
      "base": {
        "--color-text-accent": "var(--color-text-primary)"
      },
      "status:note": {
        "backgroundColor": "var(--color-background-muted)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": [
      {
        "when": {
          "width": {
            "below": "md"
          }
        },
        "value": {
          "components": {
            "section": {
              "base": {
                "padding": "var(--spacing-6) var(--spacing-4)"
              }
            }
          }
        }
      },
      {
        "when": {
          "pointer": "coarse"
        },
        "value": {
          "tokens": {
            "--size-element-sm": "44px",
            "--size-element-md": "44px",
            "--size-element-lg": "48px"
          },
          "components": {
            "collapsible-trigger": {
              "base": {
                "minHeight": "var(--size-element-md)"
              }
            }
          }
        }
      },
      {
        "when": {
          "motion": "reduce"
        },
        "value": {
          "localTokens": {
            "--yb-motion-distance": "0px",
            "--yb-motion-stagger": "0ms",
            "--yb-motion-exit": "var(--duration-fast-min)",
            "--yb-motion-enter": "var(--duration-fast-min)",
            "--yb-motion-emphasis": "var(--duration-fast-min)"
          }
        }
      }
    ]
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.25
      },
      "body": {
        "family": "var(--font-fustat)",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif"
      },
      "heading": {
        "family": "var(--font-fustat)",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
        "weight": "semibold"
      },
      "code": {
        "family": "var(--font-jetbrains-mono)",
        "fallbacks": "ui-monospace, \"SF Mono\", Menlo, Consolas, monospace"
      }
    },
    "color": {
      "accent": [
        "#5B3FE0",
        "#9B7BFF"
      ],
      "neutralStyle": "cool",
      "contrast": "standard"
    },
    "motion": {
      "fast": 150,
      "medium": 350,
      "slow": 800,
      "ratio": 0.75
    }
  },

};
