/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/yb-theme.ts
 * Command: astryx theme build src/theme/yb-theme.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Banner' {
  interface BannerStatusMap {
    'note': true;
  }
}
